name: Build for Windows

on:
  push:
    branches: [ master, ci/windows ]
  pull_request:
    branches: [ master, ci/windows ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: "Build: ${{ matrix.qt_arch }}"
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        qt_arch:
          - win64_msvc2022_64

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@f03f05556819ceb3781ee2f455ec44c339d683c0 # v4
      with:
        version: "6.7.3"
        host: windows
        target: desktop
        arch: ${{ matrix.qt_arch }}
        cache: true

    - name: Build and install KDDockWidgets 2.4.0
      shell: pwsh
      run: |
        git clone --depth 1 --branch v2.4.0 https://github.com/KDAB/KDDockWidgets.git .build/kddockwidgets-src
        cmake -S .build/kddockwidgets-src -B .build/kddockwidgets-build `
          -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE/.build/deps/kddockwidgets-2.4" `
          -DKDDockWidgets_NO_SPDLOG=ON
        cmake --build .build/kddockwidgets-build --config Release --parallel
        cmake --install .build/kddockwidgets-build --config Release

    - name: Configure + build firebird-emu
      shell: pwsh
      run: |
        cmake -S . -B .build/windows-desktop -DCMAKE_BUILD_TYPE=Release
        cmake --build .build/windows-desktop --config Release --parallel

    - name: Package app
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path .build/windows-desktop/firebird-emu | Out-Null
        Copy-Item .build/windows-desktop/Release/firebird-emu.exe .build/windows-desktop/firebird-emu/
        windeployqt --qmldir=./qml --no-qmltooling .build/windows-desktop/firebird-emu/firebird-emu.exe

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
          name: firebird-emu-${{ matrix.qt_arch }}
          path: .build/windows-desktop/firebird-emu/
          if-no-files-found: error
